const classColorStop               = app.charIDToTypeID('Clrt');
const classHSBColor                = app.charIDToTypeID('HSBC');
const classTransparencyStop        = app.charIDToTypeID('TrnS');
const enumCustomStops              = app.charIDToTypeID('CstS');
const enumGreen                    = app.charIDToTypeID('Grn ');
const enumHue                      = app.charIDToTypeID('H   ');
const enumRGBColor                 = app.charIDToTypeID('RGBC');
const enumSaturation               = app.charIDToTypeID('Strt');
const enumUserStop                 = app.charIDToTypeID('UsrS');
const eventGradient                = app.charIDToTypeID('Grdn');
const eventMake                    = app.charIDToTypeID('Mk  ');
const keyBlue                      = app.charIDToTypeID('Bl  ');
const keyBrightness                = app.charIDToTypeID('Brgh');
const keyColor                     = app.charIDToTypeID('Clr ');
const keyGradient                  = app.charIDToTypeID('Grad');
const keyInterpolation             = app.charIDToTypeID('Intr');
const keyLocation                  = app.charIDToTypeID('Lctn');
const keyMidpoint                  = app.charIDToTypeID('Mdpn');
const keyName                      = app.charIDToTypeID('Nm  ');
const keyOpacity                   = app.charIDToTypeID('Opct');
const keyRed                       = app.charIDToTypeID('Rd  ');
const keyTransparency              = app.charIDToTypeID('Trns');
const keyType                      = app.charIDToTypeID('Type');
const keyUsing                     = app.charIDToTypeID('Usng');
const typeColorStopType            = app.charIDToTypeID('Clry');
const typeColors                   = app.charIDToTypeID('Clrs');
const typeGradientForm             = app.charIDToTypeID('GrdF');
const typeNULL                     = app.charIDToTypeID('null');
const unitAngle                    = app.charIDToTypeID('#Ang');
const unitPercent                  = app.charIDToTypeID('#Prc');

// Color stop is defined by RGB, location and midpoint
var gradientName = "Name";
var gradientScale = 4096.000000;
var colorStops = [];

// =======================================================
    var desc61 = new ActionDescriptor();
        var ref23 = new ActionReference();
        ref23.putClass( eventGradient );
    desc61.putReference( typeNULL, ref23 );
        var desc62 = new ActionDescriptor();
            var desc63 = new ActionDescriptor();
            desc63.putString( keyName, """Custom""" );
            desc63.putEnumerated( typeGradientForm, typeGradientForm, enumCustomStops );
            desc63.putDouble( keyInterpolation, gradientScale );
                var list10 = new ActionList();
                    var desc64 = new ActionDescriptor();
                        var desc65 = new ActionDescriptor();
                        desc65.putUnitDouble( enumHue, unitAngle, 359.994507 );
                        desc65.putDouble( enumSaturation, 100.000000 );
                        desc65.putDouble( keyBrightness, 100.000000 );
                    desc64.putObject( keyColor, classHSBColor, desc65 );
                    desc64.putEnumerated( keyType, typeColorStopType, enumUserStop );
                    desc64.putInteger( keyLocation, 0 );
                    desc64.putInteger( keyMidpoint, 50 );
                list10.putObject( classColorStop, desc64 );
                    var desc66 = new ActionDescriptor();
                        var desc67 = new ActionDescriptor();
                        desc67.putDouble( keyRed, 0.000000 );
                        desc67.putDouble( enumGreen, 255.000000 );
                        desc67.putDouble( keyBlue, 0.000000 );
                    desc66.putObject( keyColor, enumRGBColor, desc67 );
                    desc66.putEnumerated( keyType, typeColorStopType, enumUserStop );
                    desc66.putInteger( keyLocation, 2028 );
                    desc66.putInteger( keyMidpoint, 50 );
                list10.putObject( classColorStop, desc66 );
                    var desc68 = new ActionDescriptor();
                        var desc69 = new ActionDescriptor();
                        desc69.putDouble( keyRed, 0.000000 );
                        desc69.putDouble( enumGreen, 0.000000 );
                        desc69.putDouble( keyBlue, 255.000000 );
                    desc68.putObject( keyColor, enumRGBColor, desc69 );
                    desc68.putEnumerated( keyType, typeColorStopType, enumUserStop );
                    desc68.putInteger( keyLocation, 4096 );
                    desc68.putInteger( keyMidpoint, 50 );
                list10.putObject( classColorStop, desc68 );
            desc63.putList( typeColors, list10 );
                var list11 = new ActionList();
                    var desc70 = new ActionDescriptor();
                    desc70.putUnitDouble( keyOpacity, unitPercent, 100.000000 );
                    desc70.putInteger( keyLocation, 0 );
                    desc70.putInteger( keyMidpoint, 50 );
                list11.putObject( classTransparencyStop, desc70 );
                    var desc71 = new ActionDescriptor();
                    desc71.putUnitDouble( keyOpacity, unitPercent, 100.000000 );
                    desc71.putInteger( keyLocation, 4096 );
                    desc71.putInteger( keyMidpoint, 50 );
                list11.putObject( classTransparencyStop, desc71 );
            desc63.putList( keyTransparency, list11 );
        desc62.putObject( keyGradient, eventGradient, desc63 );
    desc61.putObject( keyUsing, eventGradient, desc62 );
executeAction( eventMake, desc61, DialogModes.NO );